/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Product {
  'id' : bigint,
  'featured' : boolean,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : string,
  'priceCents' : bigint,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [string, bigint, string, string, string, bigint, boolean],
    bigint
  >,
  'addSampleProducts' : ActorMethod<[], undefined>,
  'getAllCategories' : ActorMethod<[], Array<string>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'removeProduct' : ActorMethod<[bigint], undefined>,
  'updateProduct' : ActorMethod<
    [bigint, string, bigint, string, string, string, bigint, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];